### ISSUE TITLE
not able to run in real device

### ISSUE THREAD

**Issue by userkenny** [JuppOtto/Autowalk-for-Google-VR-SDK-with-Unity#1]
Hi,

Just build it and installed in real phone under android OS 7.0, Seems the script is not able to run at real device but ok to run in unity & Windows 7 64bits android SDK emulator.

Any idea? is it something  related to gyro-sensors need to enable. However the Gvrviewer & GvrreticlePointer seems working in real android phone.

**Comment by moliata** [comment]
@userkenny phone model?

**Comment by JuppOtto** [comment]
Should work with every phone model under Android 7.0. Maybe you have some misconfigurations regarding to the script?

**Comment by JuppOtto** [comment]
I think I can close this issue :)
